<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>(LilyPond note names)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.note.base.lilypond</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.note.alteration.lilypond</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.note.octave.lilypond</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.note.time.lilypond</string>
				</dict>
			</dict>
			<key>content</key>
			<string>LilyPond note or chord abbreviation</string>
			<key>match</key>
			<string>\b(do|re|mi|fa|sol|la|si|a|b|c|d|e|f|g)(eses|isis|is|es|dd|d|bb|b|sharpsharp|sharp|flatflat|flat)?('+|,+)?([0-9]+\.?)?</string>
			<key>name</key>
			<string>entity.note.lilypond</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lilypond-notenames</string>
	<key>uuid</key>
	<string>e9ed5a04-eedd-4a42-8ae5-4788ae313909</string>
</dict>
</plist>
